/*
 *  Demo_cvs.c
 *
 *  CVODES C file for the vector field named: Demo
 *
 *  This file was generated by the program VFGEN (Version:2.4.1)
 *  Generated on 23-Apr-2019 at 11:13
 */

#include <math.h>
/* Include headers for SUNDIALS v2.4.0, CVODES v2.6.0 */
#include <cvodes/cvodes.h> 
#include <cvodes/cvodes_dense.h> 
#include <nvector/nvector_serial.h> 
#include <sundials/sundials_types.h> 

typedef int (*rhs_f)(realtype, N_Vector, N_Vector, void *);
typedef int (*jac_f)(int, realtype,
                     N_Vector, N_Vector,
                     DlsMat, void*,
                     N_Vector, N_Vector, N_Vector);

typedef int (*jacp_f)(int, realtype,
                     N_Vector, N_Vector,
                     DlsMat, void*,
                     N_Vector, N_Vector, N_Vector);

typedef int (*rhs_sens)(int, realtype, N_Vector, N_Vector,
                        int, N_Vector, N_Vector,
                        void *, N_Vector, N_Vector);

typedef int (*func)(realtype, N_Vector, realtype *, void *);
typedef int (*func_sens)(realtype, N_Vector, N_Vector *, double *, void *);

typedef struct{
const int N;
const int P;
const int F;
const double* v;
const double* p;
rhs_f vf_eval;
jac_f vf_jac;
jacp_f vf_jacp;
rhs_sens vf_sens;
func vf_func;
func_sens vf_func_sens;
const char** v_names;
const char** p_names;
const char** f_names;
void*	dylib;
} ode_model;

/*
 *  The vector field.
 */

int Demo_vf(realtype t, N_Vector y_, N_Vector f_, void *params)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype C, B, A, Activation, ReactionFlux0, ReactionFlux1, ReactionFlux2, ReactionFlux3;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    C = -ABC+C_ConservedConst-AC;
    B = -ABC-AB+B_ConservedConst;
    A = -ABC-AB-AC+A_ConservedConst;
    Activation = -1.0/( exp(-( t-t_on)*inv_tau)-1.0);
    ReactionFlux0 = -kr_R0*AB+u*B*kf_R0*A;
    ReactionFlux1 =  C*kf_R1*A-AC*kr_R1;
    ReactionFlux2 = -ABC*kr_R2+kf_R2*C*AB;
    ReactionFlux3 = -kr_R3*ABC+B*kf_R3*AC;

    NV_Ith_S(f_,0) = -ReactionFlux2+ReactionFlux0;
    NV_Ith_S(f_,1) = -ReactionFlux3+ReactionFlux1;
    NV_Ith_S(f_,2) =  ReactionFlux2+ReactionFlux3;
    return 0;
    }

/*
 *  The Jacobian.
 */

int Demo_jac(int N_, realtype t,
                N_Vector y_, N_Vector fy_,
                DlsMat jac_, void *params,
                N_Vector tmp1, N_Vector tmp2, N_Vector tmp3)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    DENSE_ELEM(jac_, 0, 0) =  ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0;
    DENSE_ELEM(jac_, 0, 1) =  kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0;
    DENSE_ELEM(jac_, 0, 2) =  kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0;
    DENSE_ELEM(jac_, 1, 0) =  kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1;
    DENSE_ELEM(jac_, 1, 1) =  ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1;
    DENSE_ELEM(jac_, 1, 2) =  kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1;
    DENSE_ELEM(jac_, 2, 0) = -( ABC-C_ConservedConst+AC)*kf_R2-kf_R3*AC;
    DENSE_ELEM(jac_, 2, 1) = -kf_R3*( ABC+AB-B_ConservedConst)-kf_R2*AB;
    DENSE_ELEM(jac_, 2, 2) = -kr_R3-kf_R3*AC-kf_R2*AB-kr_R2;
    return 0;
    }
/*
 *  The Parameter Derivative.
 */

int Demo_jacp(int N_, realtype t,
                N_Vector y_, N_Vector fy_,
                DlsMat jacp_, void *params,
                N_Vector tmp1, N_Vector tmp2, N_Vector tmp3)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    DENSE_ELEM(jacp_, 0, 0) = ( ABC+AB+AC-A_ConservedConst)*u*( ABC+AB-B_ConservedConst);
    DENSE_ELEM(jacp_, 0, 1) = -AB;
    DENSE_ELEM(jacp_, 0, 4) = ( ABC-C_ConservedConst+AC)*AB;
    DENSE_ELEM(jacp_, 0, 5) = ABC;
    DENSE_ELEM(jacp_, 0, 12) = ( ABC+AB+AC-A_ConservedConst)*( ABC+AB-B_ConservedConst)*kf_R0;
    DENSE_ELEM(jacp_, 0, 14) = -kf_R2*AB;
    DENSE_ELEM(jacp_, 0, 15) = -( ABC+AB+AC-A_ConservedConst)*u*kf_R0;
    DENSE_ELEM(jacp_, 0, 16) = -u*( ABC+AB-B_ConservedConst)*kf_R0;
    DENSE_ELEM(jacp_, 1, 2) = ( ABC-C_ConservedConst+AC)*( ABC+AB+AC-A_ConservedConst);
    DENSE_ELEM(jacp_, 1, 3) = -AC;
    DENSE_ELEM(jacp_, 1, 6) = AC*( ABC+AB-B_ConservedConst);
    DENSE_ELEM(jacp_, 1, 7) = ABC;
    DENSE_ELEM(jacp_, 1, 14) = -( ABC+AB+AC-A_ConservedConst)*kf_R1;
    DENSE_ELEM(jacp_, 1, 15) = -kf_R3*AC;
    DENSE_ELEM(jacp_, 1, 16) = -( ABC-C_ConservedConst+AC)*kf_R1;
    DENSE_ELEM(jacp_, 2, 4) = -( ABC-C_ConservedConst+AC)*AB;
    DENSE_ELEM(jacp_, 2, 5) = -ABC;
    DENSE_ELEM(jacp_, 2, 6) = -AC*( ABC+AB-B_ConservedConst);
    DENSE_ELEM(jacp_, 2, 7) = -ABC;
    DENSE_ELEM(jacp_, 2, 14) = kf_R2*AB;
    DENSE_ELEM(jacp_, 2, 15) = kf_R3*AC;
    return 0;
    }

/*
 *  Sensitivity functions 
 */

int Demo_sens(int Ns_, realtype t, N_Vector y_, N_Vector ydot_,
                int iS_, N_Vector yS_, N_Vector ySdot_,
                void *params, N_Vector tmp1, N_Vector tmp2)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype S0, S1, S2;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);
    S0         = NV_Ith_S(yS_,0);
    S1         = NV_Ith_S(yS_,1);
    S2         = NV_Ith_S(yS_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    NV_Ith_S(ySdot_,0) =  S2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*S1+S0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0);
    NV_Ith_S(ySdot_,1) =  ( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*S2+S1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+S0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
    NV_Ith_S(ySdot_,2) = -( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)*S1-S0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-S2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2);

	switch (iS_) {
        case 0:
	            NV_Ith_S(ySdot_,0) += ( ABC+AB+AC-A_ConservedConst)*u*( ABC+AB-B_ConservedConst);
	        break;
        case 1:
	            NV_Ith_S(ySdot_,0) += -AB;
	        break;
        case 2:
	            NV_Ith_S(ySdot_,1) += ( ABC-C_ConservedConst+AC)*( ABC+AB+AC-A_ConservedConst);
	        break;
        case 3:
	            NV_Ith_S(ySdot_,1) += -AC;
	        break;
        case 4:
	            NV_Ith_S(ySdot_,0) += ( ABC-C_ConservedConst+AC)*AB;
	            NV_Ith_S(ySdot_,2) += -( ABC-C_ConservedConst+AC)*AB;
	        break;
        case 5:
	            NV_Ith_S(ySdot_,0) += ABC;
	            NV_Ith_S(ySdot_,2) += -ABC;
	        break;
        case 6:
	            NV_Ith_S(ySdot_,1) += AC*( ABC+AB-B_ConservedConst);
	            NV_Ith_S(ySdot_,2) += -AC*( ABC+AB-B_ConservedConst);
	        break;
        case 7:
	            NV_Ith_S(ySdot_,1) += ABC;
	            NV_Ith_S(ySdot_,2) += -ABC;
	        break;
        case 8:
	        break;
        case 9:
	        break;
        case 10:
	        break;
        case 11:
	        break;
        case 12:
	            NV_Ith_S(ySdot_,0) += ( ABC+AB+AC-A_ConservedConst)*( ABC+AB-B_ConservedConst)*kf_R0;
	        break;
        case 13:
	        break;
        case 14:
	            NV_Ith_S(ySdot_,0) += -kf_R2*AB;
	            NV_Ith_S(ySdot_,1) += -( ABC+AB+AC-A_ConservedConst)*kf_R1;
	            NV_Ith_S(ySdot_,2) += kf_R2*AB;
	        break;
        case 15:
	            NV_Ith_S(ySdot_,0) += -( ABC+AB+AC-A_ConservedConst)*u*kf_R0;
	            NV_Ith_S(ySdot_,1) += -kf_R3*AC;
	            NV_Ith_S(ySdot_,2) += kf_R3*AC;
	        break;
        case 16:
	            NV_Ith_S(ySdot_,0) += -u*( ABC+AB-B_ConservedConst)*kf_R0;
	            NV_Ith_S(ySdot_,1) += -( ABC-C_ConservedConst+AC)*kf_R1;
	        break;
	 }
    return 0;
    }

/*
 *  User-defined functions. 
 */

int Demo_func(realtype t, N_Vector y_, realtype *func_, void *params)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype C, B, A, Activation, ReactionFlux0, ReactionFlux1, ReactionFlux2, ReactionFlux3;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    C = -ABC+C_ConservedConst-AC;
    B = -ABC-AB+B_ConservedConst;
    A = -ABC-AB-AC+A_ConservedConst;
    Activation = -1.0/( exp(-( t-t_on)*inv_tau)-1.0);
    ReactionFlux0 = -kr_R0*AB+u*B*kf_R0*A;
    ReactionFlux1 =  C*kf_R1*A-AC*kr_R1;
    ReactionFlux2 = -ABC*kr_R2+kf_R2*C*AB;
    ReactionFlux3 = -kr_R3*ABC+B*kf_R3*AC;

    /* ABCoverSUM:  */
    func_[0] = ABC/( S+C+B+A);
    /* C_mon:  */
    func_[1] = C;
    /* B_mon:  */
    func_[2] = B;
    /* A_mon:  */
    func_[3] = A;
    /* A_NetFlux:  */
    func_[4] = -ReactionFlux0-ReactionFlux1;
    /* B_NetFlux:  */
    func_[5] = -ReactionFlux0-ReactionFlux3;
    /* C_NetFlux:  */
    func_[6] = -ReactionFlux2-ReactionFlux1;
    /* AB_NetFlux:  */
    func_[7] = -ReactionFlux2+ReactionFlux0;
    /* AC_NetFlux:  */
    func_[8] = -ReactionFlux3+ReactionFlux1;
    /* ABC_NetFlux:  */
    func_[9] =  ReactionFlux2+ReactionFlux3;
    return 0;
    }

/*
 *  Sensitivities of User-defined functions. 
 */

int Demo_func_sens(realtype t, N_Vector y_, N_Vector * yS_, double* ret_, void *params)
    {
    const realtype S = RCONST(9.9999999999999995e-07);
    const realtype inv_tau = RCONST(1.0000000000000000e+03);
    realtype AB, AC, ABC;
    realtype kf_R0, kr_R0, kf_R1, kr_R1, kf_R2, kr_R2, kf_R3, kr_R3, kf_R4, kr_R4, kf_R5, kr_R5, u, t_on, C_ConservedConst, B_ConservedConst, A_ConservedConst;
    realtype C, B, A, Activation, ReactionFlux0, ReactionFlux1, ReactionFlux2, ReactionFlux3;
    realtype *p_;

    p_ = (realtype *) params;

    AB         = NV_Ith_S(y_,0);
    AC         = NV_Ith_S(y_,1);
    ABC        = NV_Ith_S(y_,2);

    kf_R0      = p_[0];
    kr_R0      = p_[1];
    kf_R1      = p_[2];
    kr_R1      = p_[3];
    kf_R2      = p_[4];
    kr_R2      = p_[5];
    kf_R3      = p_[6];
    kr_R3      = p_[7];
    kf_R4      = p_[8];
    kr_R4      = p_[9];
    kf_R5      = p_[10];
    kr_R5      = p_[11];
    u          = p_[12];
    t_on       = p_[13];
    C_ConservedConst = p_[14];
    B_ConservedConst = p_[15];
    A_ConservedConst = p_[16];

    C = -ABC+C_ConservedConst-AC;
    B = -ABC-AB+B_ConservedConst;
    A = -ABC-AB-AC+A_ConservedConst;
    Activation = -1.0/( exp(-( t-t_on)*inv_tau)-1.0);
    ReactionFlux0 = -kr_R0*AB+u*B*kf_R0*A;
    ReactionFlux1 =  C*kf_R1*A-AC*kr_R1;
    ReactionFlux2 = -ABC*kr_R2+kf_R2*C*AB;
    ReactionFlux3 = -kr_R3*ABC+B*kf_R3*AC;

    realtype yS__0_0, yS__0_1, yS__0_2, yS__1_0, yS__1_1, yS__1_2, yS__2_0, yS__2_1, yS__2_2, yS__3_0, yS__3_1, yS__3_2, yS__4_0, yS__4_1, yS__4_2, yS__5_0, yS__5_1, yS__5_2, yS__6_0, yS__6_1, yS__6_2, yS__7_0, yS__7_1, yS__7_2, yS__8_0, yS__8_1, yS__8_2, yS__9_0, yS__9_1, yS__9_2, yS__10_0, yS__10_1, yS__10_2, yS__11_0, yS__11_1, yS__11_2, yS__12_0, yS__12_1, yS__12_2, yS__13_0, yS__13_1, yS__13_2, yS__14_0, yS__14_1, yS__14_2, yS__15_0, yS__15_1, yS__15_2, yS__16_0, yS__16_1, yS__16_2;
    yS__0_0 = NV_Ith_S(yS_[0 ],0);
    yS__0_1 = NV_Ith_S(yS_[0 ],1);
    yS__0_2 = NV_Ith_S(yS_[0 ],2);
    yS__1_0 = NV_Ith_S(yS_[1 ],0);
    yS__1_1 = NV_Ith_S(yS_[1 ],1);
    yS__1_2 = NV_Ith_S(yS_[1 ],2);
    yS__2_0 = NV_Ith_S(yS_[2 ],0);
    yS__2_1 = NV_Ith_S(yS_[2 ],1);
    yS__2_2 = NV_Ith_S(yS_[2 ],2);
    yS__3_0 = NV_Ith_S(yS_[3 ],0);
    yS__3_1 = NV_Ith_S(yS_[3 ],1);
    yS__3_2 = NV_Ith_S(yS_[3 ],2);
    yS__4_0 = NV_Ith_S(yS_[4 ],0);
    yS__4_1 = NV_Ith_S(yS_[4 ],1);
    yS__4_2 = NV_Ith_S(yS_[4 ],2);
    yS__5_0 = NV_Ith_S(yS_[5 ],0);
    yS__5_1 = NV_Ith_S(yS_[5 ],1);
    yS__5_2 = NV_Ith_S(yS_[5 ],2);
    yS__6_0 = NV_Ith_S(yS_[6 ],0);
    yS__6_1 = NV_Ith_S(yS_[6 ],1);
    yS__6_2 = NV_Ith_S(yS_[6 ],2);
    yS__7_0 = NV_Ith_S(yS_[7 ],0);
    yS__7_1 = NV_Ith_S(yS_[7 ],1);
    yS__7_2 = NV_Ith_S(yS_[7 ],2);
    yS__8_0 = NV_Ith_S(yS_[8 ],0);
    yS__8_1 = NV_Ith_S(yS_[8 ],1);
    yS__8_2 = NV_Ith_S(yS_[8 ],2);
    yS__9_0 = NV_Ith_S(yS_[9 ],0);
    yS__9_1 = NV_Ith_S(yS_[9 ],1);
    yS__9_2 = NV_Ith_S(yS_[9 ],2);
    yS__10_0 = NV_Ith_S(yS_[10 ],0);
    yS__10_1 = NV_Ith_S(yS_[10 ],1);
    yS__10_2 = NV_Ith_S(yS_[10 ],2);
    yS__11_0 = NV_Ith_S(yS_[11 ],0);
    yS__11_1 = NV_Ith_S(yS_[11 ],1);
    yS__11_2 = NV_Ith_S(yS_[11 ],2);
    yS__12_0 = NV_Ith_S(yS_[12 ],0);
    yS__12_1 = NV_Ith_S(yS_[12 ],1);
    yS__12_2 = NV_Ith_S(yS_[12 ],2);
    yS__13_0 = NV_Ith_S(yS_[13 ],0);
    yS__13_1 = NV_Ith_S(yS_[13 ],1);
    yS__13_2 = NV_Ith_S(yS_[13 ],2);
    yS__14_0 = NV_Ith_S(yS_[14 ],0);
    yS__14_1 = NV_Ith_S(yS_[14 ],1);
    yS__14_2 = NV_Ith_S(yS_[14 ],2);
    yS__15_0 = NV_Ith_S(yS_[15 ],0);
    yS__15_1 = NV_Ith_S(yS_[15 ],1);
    yS__15_2 = NV_Ith_S(yS_[15 ],2);
    yS__16_0 = NV_Ith_S(yS_[16 ],0);
    yS__16_1 = NV_Ith_S(yS_[16 ],1);
    yS__16_2 = NV_Ith_S(yS_[16 ],2);

    /* kf_R0:  */
        ret_[0] =  2.0*ABC*yS__0_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__0_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__0_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[1] = -yS__0_2-yS__0_1;
        ret_[2] = -yS__0_2-yS__0_0;
        ret_[3] = -yS__0_2-yS__0_0-yS__0_1;
        ret_[4] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__0_1-yS__0_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ABC+AB+AC-A_ConservedConst)*u*( ABC+AB-B_ConservedConst)+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__0_0;
        ret_[5] =  yS__0_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__0_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__0_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)-( ABC+AB+AC-A_ConservedConst)*u*( ABC+AB-B_ConservedConst);
        ret_[6] =  yS__0_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__0_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)-yS__0_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2);
        ret_[7] =  ( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__0_1+yS__0_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__0_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( ABC+AB+AC-A_ConservedConst)*u*( ABC+AB-B_ConservedConst);
        ret_[8] =  yS__0_2*( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+yS__0_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__0_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[9] = -yS__0_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-yS__0_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)-yS__0_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB);
    /* kr_R0:  */
        ret_[10] =  2.0*ABC*yS__1_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__1_2+2.0*ABC*yS__1_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[11] = -yS__1_1-yS__1_2;
        ret_[12] = -yS__1_0-yS__1_2;
        ret_[13] = -yS__1_0-yS__1_1-yS__1_2;
        ret_[14] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__1_1+AB-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__1_2+yS__1_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[15] =  yS__1_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__1_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+AB+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__1_2;
        ret_[16] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)*yS__1_2-yS__1_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__1_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[17] =  ( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__1_1+yS__1_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-AB+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__1_2;
        ret_[18] =  yS__1_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__1_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__1_2;
        ret_[19] = -( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__1_2-yS__1_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-yS__1_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* kf_R1:  */
        ret_[20] = -( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__2_2+2.0*ABC*yS__2_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__2_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[21] = -yS__2_1-yS__2_2;
        ret_[22] = -yS__2_0-yS__2_2;
        ret_[23] = -yS__2_0-yS__2_1-yS__2_2;
        ret_[24] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__2_1-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__2_2+yS__2_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)-( ABC-C_ConservedConst+AC)*( ABC+AB+AC-A_ConservedConst);
        ret_[25] =  yS__2_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__2_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__2_2;
        ret_[26] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)*yS__2_2+yS__2_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__2_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)-( ABC-C_ConservedConst+AC)*( ABC+AB+AC-A_ConservedConst);
        ret_[27] =  yS__2_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__2_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__2_2;
        ret_[28] =  yS__2_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+yS__2_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( ABC-C_ConservedConst+AC)*( ABC+AB+AC-A_ConservedConst)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__2_2;
        ret_[29] = -( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__2_2-yS__2_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-yS__2_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* kr_R1:  */
        ret_[30] = -( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__3_2+2.0*ABC*yS__3_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__3_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[31] = -yS__3_1-yS__3_2;
        ret_[32] = -yS__3_0-yS__3_2;
        ret_[33] = -yS__3_0-yS__3_1-yS__3_2;
        ret_[34] =  yS__3_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+AC-yS__3_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__3_1;
        ret_[35] =  yS__3_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__3_2+yS__3_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[36] =  yS__3_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__3_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)*yS__3_2+AC;
        ret_[37] =  yS__3_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__3_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__3_2;
        ret_[38] =  yS__3_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__3_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)-AC+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__3_2;
        ret_[39] = -( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__3_2-yS__3_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-yS__3_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB);
    /* kf_R2:  */
        ret_[40] =  2.0*ABC*yS__4_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__4_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__4_2;
        ret_[41] = -yS__4_1-yS__4_2;
        ret_[42] = -yS__4_0-yS__4_2;
        ret_[43] = -yS__4_0-yS__4_1-yS__4_2;
        ret_[44] = -yS__4_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__4_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__4_1;
        ret_[45] =  ( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__4_2+yS__4_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__4_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[46] = -yS__4_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( ABC-C_ConservedConst+AC)*AB-yS__4_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__4_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[47] =  yS__4_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__4_2+( ABC-C_ConservedConst+AC)*AB+yS__4_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[48] =  yS__4_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__4_2+yS__4_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[49] = -yS__4_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-( ABC-C_ConservedConst+AC)*AB-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__4_2-yS__4_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* kr_R2:  */
        ret_[50] =  2.0*yS__5_0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__5_2+2.0*ABC*yS__5_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[51] = -yS__5_1-yS__5_2;
        ret_[52] = -yS__5_0-yS__5_2;
        ret_[53] = -yS__5_0-yS__5_1-yS__5_2;
        ret_[54] = -( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__5_2-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__5_1+yS__5_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[55] =  yS__5_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__5_2+yS__5_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[56] =  ABC-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)*yS__5_2+yS__5_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__5_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[57] =  yS__5_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+ABC+yS__5_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__5_2;
        ret_[58] =  yS__5_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__5_2+yS__5_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[59] = -ABC-yS__5_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__5_2-yS__5_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* kf_R3:  */
        ret_[60] = -( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__6_2+2.0*ABC*yS__6_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__6_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[61] = -yS__6_1-yS__6_2;
        ret_[62] = -yS__6_0-yS__6_2;
        ret_[63] = -yS__6_0-yS__6_1-yS__6_2;
        ret_[64] =  yS__6_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)-yS__6_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__6_1;
        ret_[65] =  yS__6_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__6_2+yS__6_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+AC*( ABC+AB-B_ConservedConst);
        ret_[66] = -yS__6_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__6_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)*yS__6_2;
        ret_[67] =  yS__6_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__6_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__6_2;
        ret_[68] =  yS__6_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__6_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__6_2+AC*( ABC+AB-B_ConservedConst);
        ret_[69] = -( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__6_2-yS__6_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-yS__6_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-AC*( ABC+AB-B_ConservedConst);
    /* kr_R3:  */
        ret_[70] =  2.0*ABC*yS__7_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__7_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))*yS__7_2;
        ret_[71] = -yS__7_1-yS__7_2;
        ret_[72] = -yS__7_0-yS__7_2;
        ret_[73] = -yS__7_0-yS__7_1-yS__7_2;
        ret_[74] = -yS__7_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__7_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__7_1;
        ret_[75] =  ABC+yS__7_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__7_2+yS__7_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[76] = -yS__7_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)-yS__7_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__7_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[77] =  yS__7_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__7_2+yS__7_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[78] =  ABC+yS__7_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__7_2+yS__7_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[79] = -ABC-yS__7_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__7_2-yS__7_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* kf_R4:  */
        ret_[80] =  2.0*yS__8_0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__8_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__8_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[81] = -yS__8_1-yS__8_2;
        ret_[82] = -yS__8_0-yS__8_2;
        ret_[83] = -yS__8_0-yS__8_1-yS__8_2;
        ret_[84] = -yS__8_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__8_1+yS__8_0*( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[85] =  ( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__8_2+yS__8_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__8_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[86] = -yS__8_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__8_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__8_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[87] =  yS__8_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__8_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__8_2;
        ret_[88] =  yS__8_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__8_2+yS__8_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[89] = -yS__8_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-yS__8_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__8_2;
    /* kr_R4:  */
        ret_[90] =  2.0*ABC*yS__9_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__9_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__9_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[91] = -yS__9_1-yS__9_2;
        ret_[92] = -yS__9_2-yS__9_0;
        ret_[93] = -yS__9_1-yS__9_2-yS__9_0;
        ret_[94] = -yS__9_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__9_0-yS__9_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[95] =  ( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__9_2+( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__9_0+yS__9_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[96] =  ( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)*yS__9_0-yS__9_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)-yS__9_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[97] =  yS__9_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__9_0+yS__9_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[98] =  ( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__9_0+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__9_2+yS__9_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[99] = -( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)*yS__9_0-yS__9_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__9_2;
    /* kf_R5:  */
        ret_[100] =  2.0*ABC*yS__10_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__10_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__10_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[101] = -yS__10_1-yS__10_2;
        ret_[102] = -yS__10_2-yS__10_0;
        ret_[103] = -yS__10_1-yS__10_2-yS__10_0;
        ret_[104] = -yS__10_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)-yS__10_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__10_0;
        ret_[105] =  yS__10_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__10_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__10_0;
        ret_[106] =  yS__10_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__10_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)-yS__10_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2);
        ret_[107] =  ( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__10_0+yS__10_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__10_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[108] =  ( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__10_2+yS__10_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__10_0;
        ret_[109] = -yS__10_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)*yS__10_2-yS__10_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB);
    /* kr_R5:  */
        ret_[110] =  2.0*ABC*yS__11_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__11_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__11_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0));
        ret_[111] = -yS__11_1-yS__11_2;
        ret_[112] = -yS__11_2-yS__11_0;
        ret_[113] = -yS__11_1-yS__11_2-yS__11_0;
        ret_[114] = -yS__11_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-yS__11_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__11_0;
        ret_[115] =  yS__11_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__11_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__11_0;
        ret_[116] = -yS__11_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+yS__11_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__11_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2);
        ret_[117] =  ( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__11_0+yS__11_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__11_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[118] =  yS__11_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__11_0+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__11_2;
        ret_[119] = -yS__11_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)-yS__11_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-yS__11_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* u:  */
        ret_[120] =  2.0*ABC*yS__12_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__12_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*yS__12_1*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[121] = -yS__12_1-yS__12_2;
        ret_[122] = -yS__12_2-yS__12_0;
        ret_[123] = -yS__12_1-yS__12_2-yS__12_0;
        ret_[124] =  ( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__12_0-( ABC+AB+AC-A_ConservedConst)*( ABC+AB-B_ConservedConst)*kf_R0-yS__12_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-yS__12_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[125] =  yS__12_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__12_0-( ABC+AB+AC-A_ConservedConst)*( ABC+AB-B_ConservedConst)*kf_R0+yS__12_1*( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[126] = -yS__12_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__12_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__12_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[127] =  yS__12_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__12_1*( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)+( ABC+AB+AC-A_ConservedConst)*( ABC+AB-B_ConservedConst)*kf_R0+( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__12_0;
        ret_[128] =  yS__12_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__12_0+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__12_2;
        ret_[129] = -yS__12_1*( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)-yS__12_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-yS__12_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2);
    /* t_on:  */
        ret_[130] = -yS__13_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__13_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)*yS__13_1;
        ret_[131] = -yS__13_2-yS__13_1;
        ret_[132] = -yS__13_2-yS__13_0;
        ret_[133] = -yS__13_2-yS__13_0-yS__13_1;
        ret_[134] =  ( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__13_0-yS__13_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__13_1;
        ret_[135] =  ( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__13_0+yS__13_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__13_1;
        ret_[136] = -yS__13_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__13_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__13_1;
        ret_[137] =  yS__13_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__13_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__13_1;
        ret_[138] =  ( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__13_1+yS__13_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__13_2;
        ret_[139] = -yS__13_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)*yS__13_1-yS__13_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2);
    /* C_ConservedConst:  */
        ret_[140] =  2.0*ABC*yS__14_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)+2.0*ABC*yS__14_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__14_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0));
        ret_[141] = -yS__14_2-yS__14_1+1.0;
        ret_[142] = -yS__14_2-yS__14_0;
        ret_[143] = -yS__14_2-yS__14_0-yS__14_1;
        ret_[144] =  ( ABC+AB+AC-A_ConservedConst)*kf_R1+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__14_0-yS__14_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__14_1;
        ret_[145] =  ( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__14_0+( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__14_1+yS__14_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[146] =  ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__14_1-yS__14_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__14_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[147] = -kf_R2*AB+yS__14_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__14_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__14_1;
        ret_[148] = -( ABC+AB+AC-A_ConservedConst)*kf_R1+yS__14_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__14_2+yS__14_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[149] =  kf_R2*AB-yS__14_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)-( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)*yS__14_1-yS__14_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* B_ConservedConst:  */
        ret_[150] =  2.0*ABC*yS__15_1/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__15_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC*yS__15_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[151] = -yS__15_2-yS__15_1;
        ret_[152] = -yS__15_2-yS__15_0+1.0;
        ret_[153] = -yS__15_2-yS__15_0-yS__15_1;
        ret_[154] =  ( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__15_0-yS__15_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( ABC+AB+AC-A_ConservedConst)*u*kf_R0-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__15_1;
        ret_[155] = -kf_R3*AC+( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__15_0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+yS__15_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__15_1;
        ret_[156] =  yS__15_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)-yS__15_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__15_1;
        ret_[157] =  yS__15_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ABC+AB+AC-A_ConservedConst)*u*kf_R0+( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__15_1+yS__15_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0);
        ret_[158] =  ( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__15_2-kf_R3*AC+yS__15_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)+yS__15_1*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1);
        ret_[159] = -( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)*yS__15_1+kf_R3*AC-yS__15_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2)-yS__15_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC);
    /* A_ConservedConst:  */
        ret_[160] =  2.0*ABC*yS__16_0/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)-yS__16_2*( 1.0/( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst)+-3.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0))+2.0*ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0)*yS__16_1-ABC/pow( 3.0*ABC-C_ConservedConst-S+2.0*AB-B_ConservedConst+2.0*AC-A_ConservedConst,2.0);
        ret_[161] = -yS__16_2-yS__16_1;
        ret_[162] = -yS__16_2-yS__16_0;
        ret_[163] = -yS__16_2-yS__16_0-yS__16_1+1.0;
        ret_[164] =  ( ABC-C_ConservedConst+AC)*kf_R1+( kr_R0-( ABC-C_ConservedConst+AC)*kf_R1-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__16_0+u*( ABC+AB-B_ConservedConst)*kf_R0-yS__16_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-( ( ABC+AB+AC-A_ConservedConst)*kf_R1+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__16_1;
        ret_[165] =  yS__16_2*( kr_R3+kf_R3*AC-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+yS__16_0*( kf_R3*AC+kr_R0-( ABC+AB+AC-A_ConservedConst)*u*kf_R0-u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R3*( ABC+AB-B_ConservedConst)-u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__16_1+u*( ABC+AB-B_ConservedConst)*kf_R0;
        ret_[166] = -yS__16_2*( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R2)+yS__16_0*( ( ABC-C_ConservedConst+AC)*kf_R2-( ABC-C_ConservedConst+AC)*kf_R1)+( ABC-C_ConservedConst+AC)*kf_R1-( ( ABC+AB+AC-A_ConservedConst)*kf_R1-kf_R2*AB+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__16_1;
        ret_[167] =  yS__16_2*( kf_R2*AB+kr_R2+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)-u*( ABC+AB-B_ConservedConst)*kf_R0+yS__16_0*( ( ABC-C_ConservedConst+AC)*kf_R2-kr_R0+( ABC+AB+AC-A_ConservedConst)*u*kf_R0+u*( ABC+AB-B_ConservedConst)*kf_R0)+( kf_R2*AB+u*( ABC+AB-B_ConservedConst)*kf_R0)*yS__16_1;
        ret_[168] =  ( ( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*( ABC+AB-B_ConservedConst)+( ABC-C_ConservedConst+AC)*kf_R1-kr_R1)*yS__16_1-( ABC-C_ConservedConst+AC)*kf_R1+( kr_R3+( ABC+AB+AC-A_ConservedConst)*kf_R1+kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1)*yS__16_2+yS__16_0*( kf_R3*AC+( ABC-C_ConservedConst+AC)*kf_R1);
        ret_[169] = -yS__16_0*( ( ABC-C_ConservedConst+AC)*kf_R2+kf_R3*AC)-( kf_R3*( ABC+AB-B_ConservedConst)+kf_R2*AB)*yS__16_1-yS__16_2*( kr_R3+kf_R3*AC+kf_R2*AB+kr_R2);
    return 0;
    }

/* Initial conditions, names and ode_model structure */
const static double Demo_init_v[3]={
                 RCONST(0.0),
                 RCONST(0.0),
                 RCONST(0.0)
            };

const static double Demo_init_p[17]={
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(0.0000000000000000e+00),
                 RCONST(1.0),
                 RCONST(0.0),
                 RCONST(1.0000000000000000e+01),
                 RCONST(1.0000000000000000e+01),
                 RCONST(1.0000000000000000e+03)
            };
    const static char *Demo_varnames[3] = {"AB", "AC", "ABC"};
    const static char *Demo_parnames[17] = {"kf_R0", "kr_R0", "kf_R1", "kr_R1", "kf_R2", "kr_R2", "kf_R3", "kr_R3", "kf_R4", "kr_R4", "kf_R5", "kr_R5", "u", "t_on", "C_ConservedConst", "B_ConservedConst", "A_ConservedConst"};
    const static char *Demo_funcnames[10] = {"ABCoverSUM", "C_mon", "B_mon", "A_mon", "A_NetFlux", "B_NetFlux", "C_NetFlux", "AB_NetFlux", "AC_NetFlux", "ABC_NetFlux"};

ode_model  Demo_odeModel = {3, 17, 10,
                     Demo_init_v, Demo_init_p,
                     &Demo_vf, &Demo_jac, &Demo_jacp,
                     &Demo_sens,
                     &Demo_func,
                     &Demo_func_sens,
                     Demo_varnames, Demo_parnames,
                     Demo_funcnames, 0
                     };
