%
% Demo_hessp.m
%
% This MATLAB function computes the derivatives of the vector field
% defined in Demo_vf.m.
%
% hessp_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th variable
% and the j-th parameter.
%
% This file was generated by the program VFGEN (Version:2.4.1)
% Generated on 23-Apr-2019 at 11:13
%
%
function hessp_ = Demo_hessp(t,x_,p_)
    S = 1.0E-6;
    inv_tau = 1000.0;
    AB         = x_(1);
    AC         = x_(2);
    ABC        = x_(3);
    kf_R0      = p_(1);
    kr_R0      = p_(2);
    kf_R1      = p_(3);
    kr_R1      = p_(4);
    kf_R2      = p_(5);
    kr_R2      = p_(6);
    kf_R3      = p_(7);
    kr_R3      = p_(8);
    kf_R4      = p_(9);
    kr_R4      = p_(10);
    kf_R5      = p_(11);
    kr_R5      = p_(12);
    u          = p_(13);
    t_on       = p_(14);
    C_ConservedConst = p_(15);
    B_ConservedConst = p_(16);
    A_ConservedConst = p_(17);

    hessp_ = zeros(3,3,17);

    hessp_(1,1,1) = u*(AB+AC-A_ConservedConst+ABC)+(AB-B_ConservedConst+ABC)*u;
    hessp_(1,1,2) = -1;
    hessp_(1,1,5) = AC+ABC-C_ConservedConst;
    hessp_(1,1,13) = (AB-B_ConservedConst+ABC)*kf_R0+kf_R0*(AB+AC-A_ConservedConst+ABC);
    hessp_(1,1,15) = -kf_R2;
    hessp_(1,1,16) = -u*kf_R0;
    hessp_(1,1,17) = -u*kf_R0;
    hessp_(1,2,1) = (AB-B_ConservedConst+ABC)*u;
    hessp_(1,2,5) = AB;
    hessp_(1,2,13) = (AB-B_ConservedConst+ABC)*kf_R0;
    hessp_(1,2,16) = -u*kf_R0;
    hessp_(1,3,1) = u*(AB+AC-A_ConservedConst+ABC)+(AB-B_ConservedConst+ABC)*u;
    hessp_(1,3,5) = AB;
    hessp_(1,3,6) = 1;
    hessp_(1,3,13) = (AB-B_ConservedConst+ABC)*kf_R0+kf_R0*(AB+AC-A_ConservedConst+ABC);
    hessp_(1,3,16) = -u*kf_R0;
    hessp_(1,3,17) = -u*kf_R0;

    hessp_(2,1,3) = AC+ABC-C_ConservedConst;
    hessp_(2,1,7) = AC;
    hessp_(2,1,15) = -kf_R1;
    hessp_(2,2,3) = AB+2*AC-A_ConservedConst+2*ABC-C_ConservedConst;
    hessp_(2,2,4) = -1;
    hessp_(2,2,7) = AB-B_ConservedConst+ABC;
    hessp_(2,2,15) = -kf_R1;
    hessp_(2,2,16) = -kf_R3;
    hessp_(2,2,17) = -kf_R1;
    hessp_(2,3,3) = AB+2*AC-A_ConservedConst+2*ABC-C_ConservedConst;
    hessp_(2,3,7) = AC;
    hessp_(2,3,8) = 1;
    hessp_(2,3,15) = -kf_R1;
    hessp_(2,3,17) = -kf_R1;

    hessp_(3,1,5) = -AC-ABC+C_ConservedConst;
    hessp_(3,1,7) = -AC;
    hessp_(3,1,15) = kf_R2;
    hessp_(3,2,5) = -AB;
    hessp_(3,2,7) = -AB+B_ConservedConst-ABC;
    hessp_(3,2,16) = kf_R3;
    hessp_(3,3,5) = -AB;
    hessp_(3,3,6) = -1;
    hessp_(3,3,7) = -AC;
    hessp_(3,3,8) = -1;

