%
% Demo_B_mon.m
%
% MATLAB user function for the vector field: Demo
%
% This file was generated by the program VFGEN (Version:2.4.1)
% Generated on 23-Apr-2019 at 11:13
%
%
function r_ = Demo_B_mon(t,x_,p_)
    S = 1.0E-6;
    inv_tau = 1000.0;
    AB         = x_(1);
    AC         = x_(2);
    ABC        = x_(3);
    kf_R0      = p_(1);
    kr_R0      = p_(2);
    kf_R1      = p_(3);
    kr_R1      = p_(4);
    kf_R2      = p_(5);
    kr_R2      = p_(6);
    kf_R3      = p_(7);
    kr_R3      = p_(8);
    kf_R4      = p_(9);
    kr_R4      = p_(10);
    kf_R5      = p_(11);
    kr_R5      = p_(12);
    u          = p_(13);
    t_on       = p_(14);
    C_ConservedConst = p_(15);
    B_ConservedConst = p_(16);
    A_ConservedConst = p_(17);
    C = -AC-ABC+C_ConservedConst;
    B = -AB+B_ConservedConst-ABC;
    A = -AB-AC+A_ConservedConst-ABC;
    Activation = -(-1+exp((t_on-t)*inv_tau))^(-1);
    ReactionFlux0 = u*B*kf_R0*A-AB*kr_R0;
    ReactionFlux1 = kf_R1*A*C-AC*kr_R1;
    ReactionFlux2 = -ABC*kr_R2+AB*kf_R2*C;
    ReactionFlux3 = -kr_R3*ABC+B*kf_R3*AC;
    r_ = B;
