%
% Demo_hess.m
%
% This MATLAB function computes the Hessians of the vector field
% defined in Demo_vf.m.
%
% hess_(n,i,j) is the second partial derivative of the n-th component
% of the vector field, taken with respect to the i-th and j-th variables.
%
% This file was generated by the program VFGEN (Version:2.4.1)
% Generated on 23-Apr-2019 at 11:13
%
%
function hess_ = Demo_hess(t,x_,p_)
    S = 1.0E-6;
    inv_tau = 1000.0;
    AB         = x_(1);
    AC         = x_(2);
    ABC        = x_(3);
    kf_R0      = p_(1);
    kr_R0      = p_(2);
    kf_R1      = p_(3);
    kr_R1      = p_(4);
    kf_R2      = p_(5);
    kr_R2      = p_(6);
    kf_R3      = p_(7);
    kr_R3      = p_(8);
    kf_R4      = p_(9);
    kr_R4      = p_(10);
    kf_R5      = p_(11);
    kr_R5      = p_(12);
    u          = p_(13);
    t_on       = p_(14);
    C_ConservedConst = p_(15);
    B_ConservedConst = p_(16);
    A_ConservedConst = p_(17);

    hess_ = zeros(3,3,3);

    hess_(1,1,1) = 2*u*kf_R0;
    hess_(1,1,2) = u*kf_R0+kf_R2;
    hess_(1,2,1) = hess_(1,1,2);
    hess_(1,1,3) = 2*u*kf_R0+kf_R2;
    hess_(1,3,1) = hess_(1,1,3);
    hess_(1,2,3) = u*kf_R0;
    hess_(1,3,2) = hess_(1,2,3);
    hess_(1,3,3) = 2*u*kf_R0;

    hess_(2,1,2) = kf_R1+kf_R3;
    hess_(2,2,1) = hess_(2,1,2);
    hess_(2,1,3) = kf_R1;
    hess_(2,3,1) = hess_(2,1,3);
    hess_(2,2,2) = 2*kf_R1;
    hess_(2,2,3) = 2*kf_R1+kf_R3;
    hess_(2,3,2) = hess_(2,2,3);
    hess_(2,3,3) = 2*kf_R1;

    hess_(3,1,2) = -kf_R3-kf_R2;
    hess_(3,2,1) = hess_(3,1,2);
    hess_(3,1,3) = -kf_R2;
    hess_(3,3,1) = hess_(3,1,3);
    hess_(3,2,3) = -kf_R3;
    hess_(3,3,2) = hess_(3,2,3);

